### PR TITLE
Engine: get rid of warning, and make most of them fatal

### PR DESCRIPTION
**Pull request by W95Psp**
This PR fixes all OCaml warnings across the `engine/lib` dune "package" (don't know whether that's the proper wording in the dune ecosystem).
This PR also makes warning fatal, so that I don't do this kind of PR in the future

### CODE REVIEW

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
This fails to build for me 

```
# File "lib/diagnostics.ml", line 57, characters 15-21:
# 57 |     | Other of string
#                     ^^^^^^
# Error: Unbound value string_of_yojson



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build hax-engine ~dev
```

**Comment by W95Psp** [comment]
Yes, sorry, I actually pushed an extra unrelated commit on that branch.
Will make another PR for that one.

**Comment by franziskuskiefer** [comment]
I'm still getting the same error

**Comment by W95Psp** [comment]
I think that's due to the base library being updated by your Opam.
Now the other PR is merged in that one, things should compile fine. Can you try again? @franziskuskiefer

**Review by franziskuskiefer — APPROVED** [review]
Thanks!

**Pull request merged**
