### PR TITLE
Ec backend

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by W95Psp** [comment]
Just rebased your branch, now it's following `main` :)
Even if the backend is still unstable, we could merge it, so that we add CI for the examples that already pass, what do you think @strub?

**Comment by strub** [comment]
@W95Psp Ping me when you are done with the refactoring we discussed at RWC s.t. I can finalize this PR.

**Comment by strub** [comment]
Just saw your second message. I agree. I will finalize it and change the draft bit when ready.

**Comment by W95Psp** [comment]
Great, merging it now then!

**Review by W95Psp — APPROVED** [review]

**Comment by strub** [comment]
I was using the "future" tense in my message... you merged a draft PR :/

**Comment by W95Psp** [comment]
Argh, sorry, I misunderstood... (I understood you'd make another PR for updating the backend)

**Pull request merged**
