### PR TITLE
Coq backend restructure

### PR DESCRIPTION
**Pull request by cmester0**
Restructure to allow multiple backends for Coq, and get better separation.

### CODE REVIEW

**Comment by W95Psp** [comment]
Looks nice, though I'm wondering: why do you need the secret arrays & secret bytes special handling?
It should be fine now, those should actually get expanded by Rust, right?
(that's what currently happens in `main`, after PR #98, that finally get rids of macros we can just let Rust expand)

**Comment by cmester0** [comment]
Yes, you are right. I was just running the command with incorrect arguments to `-i`.

**Review by franziskuskiefer — APPROVED** [review]
:shipit:

**Review by W95Psp — APPROVED** [review]
LGTM, one thing though: could you restore a mli interface to `coq_backend.ml`?

**Pull request merged**
